/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Data;
import Controller.DataController;
import Controller.MatriksConfusion;
import Controller.UjiController;
import Model.Training.NeuralNetwork.Pelatihan;
import Model.UnsurCuaca;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author M.Hakim Amransyah
 */
public class PanelPengujian extends javax.swing.JFrame {
    
    private Data data_testing;
    private UjiController controller_pengujian;
    private Pelatihan pelatihan_terpilih;

    public PanelPengujian(PanelKelolaPelatihan daftar_pelatihan,UjiController controller_pengujian) { 
        initComponents();
        this.PanelPelatihan.add(daftar_pelatihan);
        this.controller_pengujian = controller_pengujian;
    }

    private PanelPengujian() {
        
    }
    
    public Data getData_testing() {
        return data_testing;
    }
    
     public void setDataCuaca(Data data){
      DefaultTableModel model_tabel_cuaca = (DefaultTableModel) this.Tabel_data_cuaca.getModel();
      model_tabel_cuaca.setRowCount(0);
      model_tabel_cuaca.setColumnCount(data.getJumlahAtributData());
      for(UnsurCuaca atribut : data.getUnsurCuaca()){
          Object object[] = new Object[data.getJumlahAtributData()];
          object[0] =atribut.getTanggal();
          for(int i=1;i<object.length-1;i++){
              object[i] =atribut.getAtribut_value().get(i-1);
          }
          object[object.length-1] =atribut.getKeadaan_cuaca();
          model_tabel_cuaca.addRow(object);
      }
      this.setPieChart(data.getSebaran_label(),data.getJenis_data());
      this.headeringTabel(data.getHeader());
      this.centeringDataTable();
    }
     
      private void centeringDataTable(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int i=0;i<this.Tabel_data_cuaca.getColumnCount();i++){
           this.Tabel_data_cuaca.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
           this.Tabel_data_cuaca.getColumnModel().getColumn(i).setMinWidth(130);
        }  
       
    }
    
    private void headeringTabel(String header[]){
        if(header != null && header.length != 0){
          for(int i=0;i<header.length;i++){
            this.Tabel_data_cuaca.getColumnModel().getColumn(i).setHeaderValue(header[i]);
          }   
        }
    }
     
     private void setPieChart(HashMap<String, Integer> kategori,String jenis){
      DefaultPieDataset dataset  = new DefaultPieDataset();
      dataset.setValue("Sangat Ringan",new Integer(kategori.get("Sangat_Ringan")));
      dataset.setValue("Ringan",new Integer(kategori.get("Ringan")));
      dataset.setValue("Sedang",new Integer(kategori.get("Sedang")));
      dataset.setValue("Lebat",new Integer(kategori.get("Lebat")));
      dataset.setValue("Sangat Lebat",new Integer(kategori.get("Sangat_Lebat")));
      JFreeChart chart = ChartFactory.createPieChart(jenis, dataset,true,true,false);
      PiePlot p = (PiePlot) chart.getPlot();
      ChartPanel CP = new ChartPanel(chart);
      this.chart_panel.removeAll();
      this.chart_panel.add(CP);
      this.chart_panel.validate();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optimize_option = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelData = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        piechart = new javax.swing.JPanel();
        chart_panel = new javax.swing.JPanel();
        propertidata = new javax.swing.JPanel();
        label_jumlah_data_uji = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        label_jumlah_data_testing = new javax.swing.JLabel();
        tombol = new javax.swing.JPanel();
        telusuriDataUji = new javax.swing.JButton();
        Data = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabel_data_cuaca = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jumlah_data_testing = new javax.swing.JLabel();
        PanelUji = new javax.swing.JPanel();
        daftar_pelatihan = new javax.swing.JPanel();
        PanelPelatihan = new javax.swing.JPanel();
        MuatHasilPelatihanTerpilih = new javax.swing.JButton();
        hasil_pengujian = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_matriks_confusion = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Akurasi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_f_measure = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ID_Terpilih = new javax.swing.JLabel();
        lakukanPengujian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengujian");
        setBackground(new java.awt.Color(51, 153, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setBackground(new java.awt.Color(51, 153, 102));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(811, 660));
        jTabbedPane1.setRequestFocusEnabled(false);
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);

        PanelData.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(0, 102, 102));
        jPanel20.setToolTipText("");
        jPanel20.setLayout(new java.awt.BorderLayout());

        piechart.setMaximumSize(new java.awt.Dimension(100, 222));
        piechart.setPreferredSize(new java.awt.Dimension(400, 35));
        piechart.setLayout(new javax.swing.BoxLayout(piechart, javax.swing.BoxLayout.PAGE_AXIS));

        chart_panel.setBackground(new java.awt.Color(0, 102, 102));
        chart_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        chart_panel.setMaximumSize(new java.awt.Dimension(400, 600));
        chart_panel.setMinimumSize(new java.awt.Dimension(4, 400));
        chart_panel.setPreferredSize(new java.awt.Dimension(400, 600));
        chart_panel.setLayout(new java.awt.BorderLayout());
        piechart.add(chart_panel);

        propertidata.setMaximumSize(new java.awt.Dimension(400, 300));
        propertidata.setMinimumSize(new java.awt.Dimension(200, 40));
        propertidata.setPreferredSize(new java.awt.Dimension(209, 100));
        propertidata.setLayout(new java.awt.BorderLayout());

        label_jumlah_data_uji.setBackground(new java.awt.Color(0, 153, 153));
        label_jumlah_data_uji.setMaximumSize(new java.awt.Dimension(800, 500));
        label_jumlah_data_uji.setMinimumSize(new java.awt.Dimension(200, 500));
        label_jumlah_data_uji.setPreferredSize(new java.awt.Dimension(600, 500));
        label_jumlah_data_uji.setLayout(new javax.swing.BoxLayout(label_jumlah_data_uji, javax.swing.BoxLayout.LINE_AXIS));

        jPanel23.setBackground(new java.awt.Color(51, 153, 102));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel23.setMaximumSize(new java.awt.Dimension(600, 70));
        jPanel23.setMinimumSize(new java.awt.Dimension(0, 70));
        jPanel23.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Data Uji");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(44, 44, 44))
        );

        label_jumlah_data_uji.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(0, 102, 102));
        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel24.setMaximumSize(new java.awt.Dimension(200, 70));
        jPanel24.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanel24.setPreferredSize(new java.awt.Dimension(200, 50));

        label_jumlah_data_testing.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_data_testing.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        label_jumlah_data_testing.setForeground(new java.awt.Color(255, 255, 255));
        label_jumlah_data_testing.setText("0");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(label_jumlah_data_testing)
                .addGap(92, 92, 92))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_jumlah_data_testing)
                .addGap(44, 44, 44))
        );

        label_jumlah_data_uji.add(jPanel24);

        propertidata.add(label_jumlah_data_uji, java.awt.BorderLayout.CENTER);

        piechart.add(propertidata);

        tombol.setBackground(new java.awt.Color(0, 102, 102));
        tombol.setMaximumSize(new java.awt.Dimension(400, 80));
        tombol.setMinimumSize(new java.awt.Dimension(209, 80));
        tombol.setPreferredSize(new java.awt.Dimension(209, 80));
        tombol.setLayout(new java.awt.GridLayout(1, 0));

        telusuriDataUji.setBackground(new java.awt.Color(102, 0, 102));
        telusuriDataUji.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        telusuriDataUji.setForeground(new java.awt.Color(255, 255, 255));
        telusuriDataUji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/j_data.png"))); // NOI18N
        telusuriDataUji.setText("Telusuri Data Uji");
        telusuriDataUji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telusuriDataUji.setFocusable(false);
        telusuriDataUji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telusuriDataUjiActionPerformed(evt);
            }
        });
        tombol.add(telusuriDataUji);

        piechart.add(tombol);

        jPanel20.add(piechart, java.awt.BorderLayout.LINE_END);

        Data.setBackground(new java.awt.Color(0, 102, 102));

        jScrollPane3.setBackground(new java.awt.Color(51, 153, 102));

        Tabel_data_cuaca.setBackground(new java.awt.Color(51, 153, 102));
        Tabel_data_cuaca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Tabel_data_cuaca.setForeground(new java.awt.Color(255, 255, 255));
        Tabel_data_cuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabel_data_cuaca.setToolTipText("");
        Tabel_data_cuaca.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Tabel_data_cuaca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabel_data_cuaca.setFillsViewportHeight(true);
        Tabel_data_cuaca.setGridColor(new java.awt.Color(255, 255, 255));
        Tabel_data_cuaca.setName(""); // NOI18N
        Tabel_data_cuaca.setRowHeight(30);
        Tabel_data_cuaca.setRowMargin(3);
        Tabel_data_cuaca.setSelectionBackground(new java.awt.Color(255, 255, 153));
        Tabel_data_cuaca.getTableHeader().setResizingAllowed(false);
        Tabel_data_cuaca.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(Tabel_data_cuaca);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Unsur Cuaca");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/data (2).png"))); // NOI18N

        jumlah_data_testing.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jumlah_data_testing.setForeground(new java.awt.Color(255, 255, 255));
        jumlah_data_testing.setText("0");

        javax.swing.GroupLayout DataLayout = new javax.swing.GroupLayout(Data);
        Data.setLayout(DataLayout);
        DataLayout.setHorizontalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DataLayout.createSequentialGroup()
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DataLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jumlah_data_testing))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DataLayout.setVerticalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah_data_testing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel20.add(Data, java.awt.BorderLayout.CENTER);

        PanelData.add(jPanel20, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Panel Data ", PanelData);

        PanelUji.setBackground(new java.awt.Color(51, 153, 102));
        PanelUji.setLayout(new javax.swing.BoxLayout(PanelUji, javax.swing.BoxLayout.LINE_AXIS));

        daftar_pelatihan.setPreferredSize(new java.awt.Dimension(1000, 646));
        daftar_pelatihan.setLayout(new java.awt.BorderLayout());

        PanelPelatihan.setLayout(new java.awt.BorderLayout());
        daftar_pelatihan.add(PanelPelatihan, java.awt.BorderLayout.CENTER);

        MuatHasilPelatihanTerpilih.setBackground(new java.awt.Color(102, 0, 102));
        MuatHasilPelatihanTerpilih.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        MuatHasilPelatihanTerpilih.setForeground(new java.awt.Color(255, 255, 255));
        MuatHasilPelatihanTerpilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/use.png"))); // NOI18N
        MuatHasilPelatihanTerpilih.setText("Muat Pelatihan");
        MuatHasilPelatihanTerpilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MuatHasilPelatihanTerpilih.setFocusPainted(false);
        MuatHasilPelatihanTerpilih.setPreferredSize(new java.awt.Dimension(103, 40));
        MuatHasilPelatihanTerpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuatHasilPelatihanTerpilihActionPerformed(evt);
            }
        });
        daftar_pelatihan.add(MuatHasilPelatihanTerpilih, java.awt.BorderLayout.PAGE_END);

        PanelUji.add(daftar_pelatihan);

        hasil_pengujian.setPreferredSize(new java.awt.Dimension(700, 646));
        hasil_pengujian.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        tabel_matriks_confusion.setBackground(new java.awt.Color(51, 51, 51));
        tabel_matriks_confusion.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        tabel_matriks_confusion.setForeground(new java.awt.Color(255, 255, 255));
        tabel_matriks_confusion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"    Sangat Ringan", "", null, null, null, null, null},
                {"    Ringan", null, "", null, null, null, null},
                {"    Sedang", null, null, null, null, null, null},
                {"    Lebat", null, null, null, null, null, null},
                {"   Sangat Lebat ", null, null, null, null, null, null},
                {"    Recall", null, null, null, null, null, null}
            },
            new String [] {
                "A/P", "Sangat Ringan", "Ringan", "Sedang", "Lebat", "Sangat Lebat", "Presisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_matriks_confusion.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_matriks_confusion.setRowHeight(45);
        jScrollPane2.setViewportView(tabel_matriks_confusion);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Matriks Confusion Prediksi Cuaca");

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Akurasi");

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Akurasi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Akurasi.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Akurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Akurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabel_f_measure.setBackground(new java.awt.Color(51, 51, 51));
        tabel_f_measure.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tabel_f_measure.setForeground(new java.awt.Color(255, 255, 255));
        tabel_f_measure.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Sangat Ringan", "Ringan", "Sedang", "Lebat", "Sangat Lebat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_f_measure.setRowHeight(40);
        jScrollPane1.setViewportView(tabel_f_measure);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("F- Measure");

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Id Pelatihan Terpilih");

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ID_Terpilih.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ID_Terpilih.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(ID_Terpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ID_Terpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lakukanPengujian.setBackground(new java.awt.Color(102, 0, 102));
        lakukanPengujian.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lakukanPengujian.setForeground(new java.awt.Color(255, 255, 255));
        lakukanPengujian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/testing.png"))); // NOI18N
        lakukanPengujian.setText("Lakukan Pengujian");
        lakukanPengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lakukanPengujian.setFocusPainted(false);
        lakukanPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakukanPengujianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(lakukanPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(lakukanPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        hasil_pengujian.add(jPanel1, java.awt.BorderLayout.CENTER);

        PanelUji.add(hasil_pengujian);

        jTabbedPane1.addTab("Panel Pengujian", PanelUji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telusuriDataUjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telusuriDataUjiActionPerformed
        DataController controller_data = new DataController();
        try {
            this.data_testing = controller_data.pilihData(Data,"Data Uji");          
        } catch (IOException ex) {
            Logger.getLogger(PanelPengujian.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jumlah_data_testing.setText((this.data_testing.getJumlahData())+"");  
        this.label_jumlah_data_testing.setText((this.data_testing.getJumlahData())+"");
        this.setDataCuaca(data_testing);
    }//GEN-LAST:event_telusuriDataUjiActionPerformed

    private void MuatHasilPelatihanTerpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuatHasilPelatihanTerpilihActionPerformed
         this.pelatihan_terpilih = this.controller_pengujian.muatHasilPelatihan();
         this.ID_Terpilih.setText(this.pelatihan_terpilih.getId_pelatihan()+"");
    }//GEN-LAST:event_MuatHasilPelatihanTerpilihActionPerformed

    private void lakukanPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakukanPengujianActionPerformed
        if(this.pelatihan_terpilih != null){
            MatriksConfusion hasil_pengujian = this.controller_pengujian.prediksiCuaca(data_testing, pelatihan_terpilih);
            this.setMatriksConfussion(hasil_pengujian);
        }
        else{
            JOptionPane.showMessageDialog(null,"Tidak ada pelatihan yang dimuat","Oops",JOptionPane.WARNING_MESSAGE);   
        }
    }//GEN-LAST:event_lakukanPengujianActionPerformed

    private void setMatriksConfussion(MatriksConfusion hasil_pengujian){
        if(hasil_pengujian != null){
            double matriks_confusion[][] = hasil_pengujian.getMatriksConfusion();

            for(int i=0;i<this.tabel_matriks_confusion.getRowCount();i++){
                for(int j=0;j<this.tabel_matriks_confusion.getColumnCount();j++){
                    if(i<5){
                        if(j<5){
                            this.tabel_matriks_confusion.setValueAt("              "+(int)matriks_confusion[i][j], i,j+1);
                        }else if(j == 5) {
                            if(i == 0){
                                this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentasePresisi("Sangat Ringan")+" %", i,j+1);
                            }else if(i == 1){
                                this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentasePresisi("Ringan")+" %", i,j+1);
                            }else if(i == 2){
                                this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentasePresisi("Sedang")+" %", i,j+1);
                            }else if(i == 3){
                                this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentasePresisi("Lebat")+" %", i,j+1);
                            }else if(i == 4){
                                this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentasePresisi("Sangat Lebat")+" %", i,j+1);
                            }
                        }
                    }else if(i == 5){
                        if(j == 0){
                            this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentaseRecall("Sangat Ringan")+" %", i,j+1);
                        }else if(j == 1){
                            this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentaseRecall("Ringan")+" %", i,j+1);
                        }else if(j == 2){
                            this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentaseRecall("Sedang")+" %", i,j+1);
                        }else if(j == 3){
                            this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentaseRecall("Lebat")+" %", i,j+1);
                        }else if(j == 4){
                            this.tabel_matriks_confusion.setValueAt("         "+hasil_pengujian.getPersentaseRecall("Sangat Lebat")+" %", i,j+1);
                        }else if(j == 5){
                            this.tabel_matriks_confusion.setValueAt("          "+hasil_pengujian.getAkurasi()+" %", i,j+1);
                        }
                    }
                }
            }
            this.Akurasi.setText(hasil_pengujian.getAkurasi()+" %");
            this.setFmeasureTabel(hasil_pengujian);
        }
    }
    
    private void setFmeasureTabel(MatriksConfusion hasil_pengujian){
        for(int i=0;i<this.tabel_f_measure.getColumnCount();i++){
            if(i==0){
                this.tabel_f_measure.setValueAt("                "+hasil_pengujian.getFmeasure("Sangat Ringan")+" %", 0,i);
            }else if(i ==1){
                this.tabel_f_measure.setValueAt("                "+hasil_pengujian.getFmeasure("Ringan")+" %", 0,i);
            }else if(i==2){
                this.tabel_f_measure.setValueAt("                "+hasil_pengujian.getFmeasure("Sedang")+" %", 0,i);
            }else if(i==3){
                this.tabel_f_measure.setValueAt("                "+hasil_pengujian.getFmeasure("Lebat")+" %", 0,i);
            }else if(i==4){
                this.tabel_f_measure.setValueAt("                "+hasil_pengujian.getFmeasure("Sangat Lebat")+" %", 0,i);
            }
        }
    }
 



    
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPengujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPengujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPengujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPengujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPengujian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Akurasi;
    private javax.swing.JPanel Data;
    private javax.swing.JLabel ID_Terpilih;
    private javax.swing.JButton MuatHasilPelatihanTerpilih;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelPelatihan;
    private javax.swing.JPanel PanelUji;
    private javax.swing.JTable Tabel_data_cuaca;
    private javax.swing.JPanel chart_panel;
    private javax.swing.JPanel daftar_pelatihan;
    private javax.swing.JPanel hasil_pengujian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jumlah_data_testing;
    private javax.swing.JLabel label_jumlah_data_testing;
    private javax.swing.JPanel label_jumlah_data_uji;
    private javax.swing.JButton lakukanPengujian;
    private javax.swing.ButtonGroup optimize_option;
    private javax.swing.JPanel piechart;
    private javax.swing.JPanel propertidata;
    private javax.swing.JTable tabel_f_measure;
    private javax.swing.JTable tabel_matriks_confusion;
    private javax.swing.JButton telusuriDataUji;
    private javax.swing.JPanel tombol;
    // End of variables declaration//GEN-END:variables
}
